# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app-request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app-request.proto',
  package='',
  serialized_pb='\n\x11\x61pp-request.proto\"\xd8\x01\n\x11\x41ppRequestMessage\x12/\n\x07\x63ommand\x18\xdf\x01 \x02(\x0b\x32\x1d.AppRequestMessage.AppRequest\x1a\x1a\n\x04Name\x12\x12\n\ncomponents\x18\x08 \x03(\x0c\x1av\n\nAppRequest\x12(\n\x06idName\x18\xdc\x01 \x02(\x0b\x32\x17.AppRequestMessage.Name\x12,\n\ndataPrefix\x18\xdd\x01 \x02(\x0b\x32\x17.AppRequestMessage.Name\x12\x10\n\x07\x61ppName\x18\xde\x01 \x02(\t')




_APPREQUESTMESSAGE_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='AppRequestMessage.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='components', full_name='AppRequestMessage.Name.components', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=92,
  serialized_end=118,
)

_APPREQUESTMESSAGE_APPREQUEST = _descriptor.Descriptor(
  name='AppRequest',
  full_name='AppRequestMessage.AppRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='idName', full_name='AppRequestMessage.AppRequest.idName', index=0,
      number=220, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataPrefix', full_name='AppRequestMessage.AppRequest.dataPrefix', index=1,
      number=221, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appName', full_name='AppRequestMessage.AppRequest.appName', index=2,
      number=222, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=120,
  serialized_end=238,
)

_APPREQUESTMESSAGE = _descriptor.Descriptor(
  name='AppRequestMessage',
  full_name='AppRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='AppRequestMessage.command', index=0,
      number=223, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_APPREQUESTMESSAGE_NAME, _APPREQUESTMESSAGE_APPREQUEST, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=238,
)

_APPREQUESTMESSAGE_NAME.containing_type = _APPREQUESTMESSAGE;
_APPREQUESTMESSAGE_APPREQUEST.fields_by_name['idName'].message_type = _APPREQUESTMESSAGE_NAME
_APPREQUESTMESSAGE_APPREQUEST.fields_by_name['dataPrefix'].message_type = _APPREQUESTMESSAGE_NAME
_APPREQUESTMESSAGE_APPREQUEST.containing_type = _APPREQUESTMESSAGE;
_APPREQUESTMESSAGE.fields_by_name['command'].message_type = _APPREQUESTMESSAGE_APPREQUEST
DESCRIPTOR.message_types_by_name['AppRequestMessage'] = _APPREQUESTMESSAGE

class AppRequestMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Name(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _APPREQUESTMESSAGE_NAME

    # @@protoc_insertion_point(class_scope:AppRequestMessage.Name)

  class AppRequest(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _APPREQUESTMESSAGE_APPREQUEST

    # @@protoc_insertion_point(class_scope:AppRequestMessage.AppRequest)
  DESCRIPTOR = _APPREQUESTMESSAGE

  # @@protoc_insertion_point(class_scope:AppRequestMessage)


# @@protoc_insertion_point(module_scope)
