// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app-request.proto

#ifndef PROTOBUF_app_2drequest_2eproto__INCLUDED
#define PROTOBUF_app_2drequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_app_2drequest_2eproto();
void protobuf_AssignDesc_app_2drequest_2eproto();
void protobuf_ShutdownFile_app_2drequest_2eproto();

class AppRequestMessage;
class AppRequestMessage_Name;
class AppRequestMessage_AppRequest;

// ===================================================================

class AppRequestMessage_Name : public ::google::protobuf::Message {
 public:
  AppRequestMessage_Name();
  virtual ~AppRequestMessage_Name();

  AppRequestMessage_Name(const AppRequestMessage_Name& from);

  inline AppRequestMessage_Name& operator=(const AppRequestMessage_Name& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppRequestMessage_Name& default_instance();

  void Swap(AppRequestMessage_Name* other);

  // implements Message ----------------------------------------------

  AppRequestMessage_Name* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppRequestMessage_Name& from);
  void MergeFrom(const AppRequestMessage_Name& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes components = 8;
  inline int components_size() const;
  inline void clear_components();
  static const int kComponentsFieldNumber = 8;
  inline const ::std::string& components(int index) const;
  inline ::std::string* mutable_components(int index);
  inline void set_components(int index, const ::std::string& value);
  inline void set_components(int index, const char* value);
  inline void set_components(int index, const void* value, size_t size);
  inline ::std::string* add_components();
  inline void add_components(const ::std::string& value);
  inline void add_components(const char* value);
  inline void add_components(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& components() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_components();

  // @@protoc_insertion_point(class_scope:AppRequestMessage.Name)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> components_;
  friend void  protobuf_AddDesc_app_2drequest_2eproto();
  friend void protobuf_AssignDesc_app_2drequest_2eproto();
  friend void protobuf_ShutdownFile_app_2drequest_2eproto();

  void InitAsDefaultInstance();
  static AppRequestMessage_Name* default_instance_;
};
// -------------------------------------------------------------------

class AppRequestMessage_AppRequest : public ::google::protobuf::Message {
 public:
  AppRequestMessage_AppRequest();
  virtual ~AppRequestMessage_AppRequest();

  AppRequestMessage_AppRequest(const AppRequestMessage_AppRequest& from);

  inline AppRequestMessage_AppRequest& operator=(const AppRequestMessage_AppRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppRequestMessage_AppRequest& default_instance();

  void Swap(AppRequestMessage_AppRequest* other);

  // implements Message ----------------------------------------------

  AppRequestMessage_AppRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppRequestMessage_AppRequest& from);
  void MergeFrom(const AppRequestMessage_AppRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .AppRequestMessage.Name idName = 220;
  inline bool has_idname() const;
  inline void clear_idname();
  static const int kIdNameFieldNumber = 220;
  inline const ::AppRequestMessage_Name& idname() const;
  inline ::AppRequestMessage_Name* mutable_idname();
  inline ::AppRequestMessage_Name* release_idname();
  inline void set_allocated_idname(::AppRequestMessage_Name* idname);

  // required .AppRequestMessage.Name dataPrefix = 221;
  inline bool has_dataprefix() const;
  inline void clear_dataprefix();
  static const int kDataPrefixFieldNumber = 221;
  inline const ::AppRequestMessage_Name& dataprefix() const;
  inline ::AppRequestMessage_Name* mutable_dataprefix();
  inline ::AppRequestMessage_Name* release_dataprefix();
  inline void set_allocated_dataprefix(::AppRequestMessage_Name* dataprefix);

  // required string appName = 222;
  inline bool has_appname() const;
  inline void clear_appname();
  static const int kAppNameFieldNumber = 222;
  inline const ::std::string& appname() const;
  inline void set_appname(const ::std::string& value);
  inline void set_appname(const char* value);
  inline void set_appname(const char* value, size_t size);
  inline ::std::string* mutable_appname();
  inline ::std::string* release_appname();
  inline void set_allocated_appname(::std::string* appname);

  // @@protoc_insertion_point(class_scope:AppRequestMessage.AppRequest)
 private:
  inline void set_has_idname();
  inline void clear_has_idname();
  inline void set_has_dataprefix();
  inline void clear_has_dataprefix();
  inline void set_has_appname();
  inline void clear_has_appname();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::AppRequestMessage_Name* idname_;
  ::AppRequestMessage_Name* dataprefix_;
  ::std::string* appname_;
  friend void  protobuf_AddDesc_app_2drequest_2eproto();
  friend void protobuf_AssignDesc_app_2drequest_2eproto();
  friend void protobuf_ShutdownFile_app_2drequest_2eproto();

  void InitAsDefaultInstance();
  static AppRequestMessage_AppRequest* default_instance_;
};
// -------------------------------------------------------------------

class AppRequestMessage : public ::google::protobuf::Message {
 public:
  AppRequestMessage();
  virtual ~AppRequestMessage();

  AppRequestMessage(const AppRequestMessage& from);

  inline AppRequestMessage& operator=(const AppRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AppRequestMessage& default_instance();

  void Swap(AppRequestMessage* other);

  // implements Message ----------------------------------------------

  AppRequestMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AppRequestMessage& from);
  void MergeFrom(const AppRequestMessage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef AppRequestMessage_Name Name;
  typedef AppRequestMessage_AppRequest AppRequest;

  // accessors -------------------------------------------------------

  // required .AppRequestMessage.AppRequest command = 223;
  inline bool has_command() const;
  inline void clear_command();
  static const int kCommandFieldNumber = 223;
  inline const ::AppRequestMessage_AppRequest& command() const;
  inline ::AppRequestMessage_AppRequest* mutable_command();
  inline ::AppRequestMessage_AppRequest* release_command();
  inline void set_allocated_command(::AppRequestMessage_AppRequest* command);

  // @@protoc_insertion_point(class_scope:AppRequestMessage)
 private:
  inline void set_has_command();
  inline void clear_has_command();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::AppRequestMessage_AppRequest* command_;
  friend void  protobuf_AddDesc_app_2drequest_2eproto();
  friend void protobuf_AssignDesc_app_2drequest_2eproto();
  friend void protobuf_ShutdownFile_app_2drequest_2eproto();

  void InitAsDefaultInstance();
  static AppRequestMessage* default_instance_;
};
// ===================================================================


// ===================================================================

// AppRequestMessage_Name

// repeated bytes components = 8;
inline int AppRequestMessage_Name::components_size() const {
  return components_.size();
}
inline void AppRequestMessage_Name::clear_components() {
  components_.Clear();
}
inline const ::std::string& AppRequestMessage_Name::components(int index) const {
  // @@protoc_insertion_point(field_get:AppRequestMessage.Name.components)
  return components_.Get(index);
}
inline ::std::string* AppRequestMessage_Name::mutable_components(int index) {
  // @@protoc_insertion_point(field_mutable:AppRequestMessage.Name.components)
  return components_.Mutable(index);
}
inline void AppRequestMessage_Name::set_components(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:AppRequestMessage.Name.components)
  components_.Mutable(index)->assign(value);
}
inline void AppRequestMessage_Name::set_components(int index, const char* value) {
  components_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:AppRequestMessage.Name.components)
}
inline void AppRequestMessage_Name::set_components(int index, const void* value, size_t size) {
  components_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:AppRequestMessage.Name.components)
}
inline ::std::string* AppRequestMessage_Name::add_components() {
  return components_.Add();
}
inline void AppRequestMessage_Name::add_components(const ::std::string& value) {
  components_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:AppRequestMessage.Name.components)
}
inline void AppRequestMessage_Name::add_components(const char* value) {
  components_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:AppRequestMessage.Name.components)
}
inline void AppRequestMessage_Name::add_components(const void* value, size_t size) {
  components_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:AppRequestMessage.Name.components)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
AppRequestMessage_Name::components() const {
  // @@protoc_insertion_point(field_list:AppRequestMessage.Name.components)
  return components_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
AppRequestMessage_Name::mutable_components() {
  // @@protoc_insertion_point(field_mutable_list:AppRequestMessage.Name.components)
  return &components_;
}

// -------------------------------------------------------------------

// AppRequestMessage_AppRequest

// required .AppRequestMessage.Name idName = 220;
inline bool AppRequestMessage_AppRequest::has_idname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppRequestMessage_AppRequest::set_has_idname() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppRequestMessage_AppRequest::clear_has_idname() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppRequestMessage_AppRequest::clear_idname() {
  if (idname_ != NULL) idname_->::AppRequestMessage_Name::Clear();
  clear_has_idname();
}
inline const ::AppRequestMessage_Name& AppRequestMessage_AppRequest::idname() const {
  // @@protoc_insertion_point(field_get:AppRequestMessage.AppRequest.idName)
  return idname_ != NULL ? *idname_ : *default_instance_->idname_;
}
inline ::AppRequestMessage_Name* AppRequestMessage_AppRequest::mutable_idname() {
  set_has_idname();
  if (idname_ == NULL) idname_ = new ::AppRequestMessage_Name;
  // @@protoc_insertion_point(field_mutable:AppRequestMessage.AppRequest.idName)
  return idname_;
}
inline ::AppRequestMessage_Name* AppRequestMessage_AppRequest::release_idname() {
  clear_has_idname();
  ::AppRequestMessage_Name* temp = idname_;
  idname_ = NULL;
  return temp;
}
inline void AppRequestMessage_AppRequest::set_allocated_idname(::AppRequestMessage_Name* idname) {
  delete idname_;
  idname_ = idname;
  if (idname) {
    set_has_idname();
  } else {
    clear_has_idname();
  }
  // @@protoc_insertion_point(field_set_allocated:AppRequestMessage.AppRequest.idName)
}

// required .AppRequestMessage.Name dataPrefix = 221;
inline bool AppRequestMessage_AppRequest::has_dataprefix() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void AppRequestMessage_AppRequest::set_has_dataprefix() {
  _has_bits_[0] |= 0x00000002u;
}
inline void AppRequestMessage_AppRequest::clear_has_dataprefix() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void AppRequestMessage_AppRequest::clear_dataprefix() {
  if (dataprefix_ != NULL) dataprefix_->::AppRequestMessage_Name::Clear();
  clear_has_dataprefix();
}
inline const ::AppRequestMessage_Name& AppRequestMessage_AppRequest::dataprefix() const {
  // @@protoc_insertion_point(field_get:AppRequestMessage.AppRequest.dataPrefix)
  return dataprefix_ != NULL ? *dataprefix_ : *default_instance_->dataprefix_;
}
inline ::AppRequestMessage_Name* AppRequestMessage_AppRequest::mutable_dataprefix() {
  set_has_dataprefix();
  if (dataprefix_ == NULL) dataprefix_ = new ::AppRequestMessage_Name;
  // @@protoc_insertion_point(field_mutable:AppRequestMessage.AppRequest.dataPrefix)
  return dataprefix_;
}
inline ::AppRequestMessage_Name* AppRequestMessage_AppRequest::release_dataprefix() {
  clear_has_dataprefix();
  ::AppRequestMessage_Name* temp = dataprefix_;
  dataprefix_ = NULL;
  return temp;
}
inline void AppRequestMessage_AppRequest::set_allocated_dataprefix(::AppRequestMessage_Name* dataprefix) {
  delete dataprefix_;
  dataprefix_ = dataprefix;
  if (dataprefix) {
    set_has_dataprefix();
  } else {
    clear_has_dataprefix();
  }
  // @@protoc_insertion_point(field_set_allocated:AppRequestMessage.AppRequest.dataPrefix)
}

// required string appName = 222;
inline bool AppRequestMessage_AppRequest::has_appname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void AppRequestMessage_AppRequest::set_has_appname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void AppRequestMessage_AppRequest::clear_has_appname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void AppRequestMessage_AppRequest::clear_appname() {
  if (appname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appname_->clear();
  }
  clear_has_appname();
}
inline const ::std::string& AppRequestMessage_AppRequest::appname() const {
  // @@protoc_insertion_point(field_get:AppRequestMessage.AppRequest.appName)
  return *appname_;
}
inline void AppRequestMessage_AppRequest::set_appname(const ::std::string& value) {
  set_has_appname();
  if (appname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appname_ = new ::std::string;
  }
  appname_->assign(value);
  // @@protoc_insertion_point(field_set:AppRequestMessage.AppRequest.appName)
}
inline void AppRequestMessage_AppRequest::set_appname(const char* value) {
  set_has_appname();
  if (appname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appname_ = new ::std::string;
  }
  appname_->assign(value);
  // @@protoc_insertion_point(field_set_char:AppRequestMessage.AppRequest.appName)
}
inline void AppRequestMessage_AppRequest::set_appname(const char* value, size_t size) {
  set_has_appname();
  if (appname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appname_ = new ::std::string;
  }
  appname_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:AppRequestMessage.AppRequest.appName)
}
inline ::std::string* AppRequestMessage_AppRequest::mutable_appname() {
  set_has_appname();
  if (appname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    appname_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:AppRequestMessage.AppRequest.appName)
  return appname_;
}
inline ::std::string* AppRequestMessage_AppRequest::release_appname() {
  clear_has_appname();
  if (appname_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = appname_;
    appname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void AppRequestMessage_AppRequest::set_allocated_appname(::std::string* appname) {
  if (appname_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete appname_;
  }
  if (appname) {
    set_has_appname();
    appname_ = appname;
  } else {
    clear_has_appname();
    appname_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:AppRequestMessage.AppRequest.appName)
}

// -------------------------------------------------------------------

// AppRequestMessage

// required .AppRequestMessage.AppRequest command = 223;
inline bool AppRequestMessage::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AppRequestMessage::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AppRequestMessage::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AppRequestMessage::clear_command() {
  if (command_ != NULL) command_->::AppRequestMessage_AppRequest::Clear();
  clear_has_command();
}
inline const ::AppRequestMessage_AppRequest& AppRequestMessage::command() const {
  // @@protoc_insertion_point(field_get:AppRequestMessage.command)
  return command_ != NULL ? *command_ : *default_instance_->command_;
}
inline ::AppRequestMessage_AppRequest* AppRequestMessage::mutable_command() {
  set_has_command();
  if (command_ == NULL) command_ = new ::AppRequestMessage_AppRequest;
  // @@protoc_insertion_point(field_mutable:AppRequestMessage.command)
  return command_;
}
inline ::AppRequestMessage_AppRequest* AppRequestMessage::release_command() {
  clear_has_command();
  ::AppRequestMessage_AppRequest* temp = command_;
  command_ = NULL;
  return temp;
}
inline void AppRequestMessage::set_allocated_command(::AppRequestMessage_AppRequest* command) {
  delete command_;
  command_ = command;
  if (command) {
    set_has_command();
  } else {
    clear_has_command();
  }
  // @@protoc_insertion_point(field_set_allocated:AppRequestMessage.command)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_app_2drequest_2eproto__INCLUDED
