// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app-request-proto3.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ndn_iot.bootstrap.command {

  /// <summary>Holder for reflection information generated from app-request-proto3.proto</summary>
  public static partial class AppRequestProto3Reflection {

    #region Descriptor
    /// <summary>File descriptor for app-request-proto3.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AppRequestProto3Reflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChhhcHAtcmVxdWVzdC1wcm90bzMucHJvdG8i2AEKEUFwcFJlcXVlc3RNZXNz",
            "YWdlEi8KB2NvbW1hbmQY3wEgASgLMh0uQXBwUmVxdWVzdE1lc3NhZ2UuQXBw",
            "UmVxdWVzdBoaCgROYW1lEhIKCmNvbXBvbmVudHMYCCADKAwadgoKQXBwUmVx",
            "dWVzdBIoCgZpZE5hbWUY3AEgASgLMhcuQXBwUmVxdWVzdE1lc3NhZ2UuTmFt",
            "ZRIsCgpkYXRhUHJlZml4GN0BIAEoCzIXLkFwcFJlcXVlc3RNZXNzYWdlLk5h",
            "bWUSEAoHYXBwTmFtZRjeASABKAlCHKoCGW5kbl9pb3QuYm9vdHN0cmFwLmNv",
            "bW1hbmRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ndn_iot.bootstrap.command.AppRequestMessage), global::ndn_iot.bootstrap.command.AppRequestMessage.Parser, new[]{ "Command" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name), global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name.Parser, new[]{ "Components" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ndn_iot.bootstrap.command.AppRequestMessage.Types.AppRequest), global::ndn_iot.bootstrap.command.AppRequestMessage.Types.AppRequest.Parser, new[]{ "IdName", "DataPrefix", "AppName" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AppRequestMessage : pb::IMessage<AppRequestMessage> {
    private static readonly pb::MessageParser<AppRequestMessage> _parser = new pb::MessageParser<AppRequestMessage>(() => new AppRequestMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AppRequestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ndn_iot.bootstrap.command.AppRequestProto3Reflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AppRequestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AppRequestMessage(AppRequestMessage other) : this() {
      Command = other.command_ != null ? other.Command.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AppRequestMessage Clone() {
      return new AppRequestMessage(this);
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 223;
    private global::ndn_iot.bootstrap.command.AppRequestMessage.Types.AppRequest command_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ndn_iot.bootstrap.command.AppRequestMessage.Types.AppRequest Command {
      get { return command_; }
      set {
        command_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AppRequestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AppRequestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Command, other.Command)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (command_ != null) hash ^= Command.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (command_ != null) {
        output.WriteRawTag(250, 13);
        output.WriteMessage(Command);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (command_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Command);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AppRequestMessage other) {
      if (other == null) {
        return;
      }
      if (other.command_ != null) {
        if (command_ == null) {
          command_ = new global::ndn_iot.bootstrap.command.AppRequestMessage.Types.AppRequest();
        }
        Command.MergeFrom(other.Command);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 1786: {
            if (command_ == null) {
              command_ = new global::ndn_iot.bootstrap.command.AppRequestMessage.Types.AppRequest();
            }
            input.ReadMessage(command_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AppRequestMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Name : pb::IMessage<Name> {
        private static readonly pb::MessageParser<Name> _parser = new pb::MessageParser<Name>(() => new Name());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Name> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ndn_iot.bootstrap.command.AppRequestMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Name() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Name(Name other) : this() {
          components_ = other.components_.Clone();
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Name Clone() {
          return new Name(this);
        }

        /// <summary>Field number for the "components" field.</summary>
        public const int ComponentsFieldNumber = 8;
        private static readonly pb::FieldCodec<pb::ByteString> _repeated_components_codec
            = pb::FieldCodec.ForBytes(66);
        private readonly pbc::RepeatedField<pb::ByteString> components_ = new pbc::RepeatedField<pb::ByteString>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public pbc::RepeatedField<pb::ByteString> Components {
          get { return components_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Name);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Name other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!components_.Equals(other.components_)) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= components_.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          components_.WriteTo(output, _repeated_components_codec);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          size += components_.CalculateSize(_repeated_components_codec);
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Name other) {
          if (other == null) {
            return;
          }
          components_.Add(other.components_);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 66: {
                components_.AddEntriesFrom(input, _repeated_components_codec);
                break;
              }
            }
          }
        }

      }

      public sealed partial class AppRequest : pb::IMessage<AppRequest> {
        private static readonly pb::MessageParser<AppRequest> _parser = new pb::MessageParser<AppRequest>(() => new AppRequest());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<AppRequest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::ndn_iot.bootstrap.command.AppRequestMessage.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AppRequest() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AppRequest(AppRequest other) : this() {
          IdName = other.idName_ != null ? other.IdName.Clone() : null;
          DataPrefix = other.dataPrefix_ != null ? other.DataPrefix.Clone() : null;
          appName_ = other.appName_;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public AppRequest Clone() {
          return new AppRequest(this);
        }

        /// <summary>Field number for the "idName" field.</summary>
        public const int IdNameFieldNumber = 220;
        private global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name idName_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name IdName {
          get { return idName_; }
          set {
            idName_ = value;
          }
        }

        /// <summary>Field number for the "dataPrefix" field.</summary>
        public const int DataPrefixFieldNumber = 221;
        private global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name dataPrefix_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name DataPrefix {
          get { return dataPrefix_; }
          set {
            dataPrefix_ = value;
          }
        }

        /// <summary>Field number for the "appName" field.</summary>
        public const int AppNameFieldNumber = 222;
        private string appName_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string AppName {
          get { return appName_; }
          set {
            appName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as AppRequest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(AppRequest other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!object.Equals(IdName, other.IdName)) return false;
          if (!object.Equals(DataPrefix, other.DataPrefix)) return false;
          if (AppName != other.AppName) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (idName_ != null) hash ^= IdName.GetHashCode();
          if (dataPrefix_ != null) hash ^= DataPrefix.GetHashCode();
          if (AppName.Length != 0) hash ^= AppName.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (idName_ != null) {
            output.WriteRawTag(226, 13);
            output.WriteMessage(IdName);
          }
          if (dataPrefix_ != null) {
            output.WriteRawTag(234, 13);
            output.WriteMessage(DataPrefix);
          }
          if (AppName.Length != 0) {
            output.WriteRawTag(242, 13);
            output.WriteString(AppName);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (idName_ != null) {
            size += 2 + pb::CodedOutputStream.ComputeMessageSize(IdName);
          }
          if (dataPrefix_ != null) {
            size += 2 + pb::CodedOutputStream.ComputeMessageSize(DataPrefix);
          }
          if (AppName.Length != 0) {
            size += 2 + pb::CodedOutputStream.ComputeStringSize(AppName);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(AppRequest other) {
          if (other == null) {
            return;
          }
          if (other.idName_ != null) {
            if (idName_ == null) {
              idName_ = new global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name();
            }
            IdName.MergeFrom(other.IdName);
          }
          if (other.dataPrefix_ != null) {
            if (dataPrefix_ == null) {
              dataPrefix_ = new global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name();
            }
            DataPrefix.MergeFrom(other.DataPrefix);
          }
          if (other.AppName.Length != 0) {
            AppName = other.AppName;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 1762: {
                if (idName_ == null) {
                  idName_ = new global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name();
                }
                input.ReadMessage(idName_);
                break;
              }
              case 1770: {
                if (dataPrefix_ == null) {
                  dataPrefix_ = new global::ndn_iot.bootstrap.command.AppRequestMessage.Types.Name();
                }
                input.ReadMessage(dataPrefix_);
                break;
              }
              case 1778: {
                AppName = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
